# -*- coding: utf-8 -*-
"""final_project_Bachdar_data_heacktiv8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16V3rym-wQCiQVUg5W7XD5dzgqnjJRP2A
"""

!pip install langchain_community
!pip install replicate

from google.colab import userdata
import os

#ambil token dari colab
api_token = userdata.get('api_token')
#taro token keenvronment variable
os.environ['REPLICATE_API_TOKEN']= api_token

from langchain_community.llms import Replicate
# Ambil granite dari replicate

llm = Replicate(
     model="ibm-granite/granite-3.3-8b-instruct"
)

output = llm.invoke("where is elonk musk stay now")
print(output)

!pip install pandas
!pip install -U langchain langchain-community langchain-experimental replicate

import pandas as pd

df = pd.read_csv("SMSSpamCollection", sep="\t", names=["label", "text"], header=None)
print("Jumlah baris & kolom:", df.shape)

df.head()

# ================================
# EDA Lengkap SMS Spam Collection
# ================================
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display
from wordcloud import WordCloud

# --- 1. Load dataset ---
df = pd.read_csv("SMSSpamCollection", sep="\t", names=["label", "text"], header=None)

# --- 2. Tabel 10 data pertama ---
print("📌 Contoh 10 Pesan Pertama:")
display(df.head(10))

# --- 3. Distribusi label (tabel + barplot) ---
label_dist = df["label"].value_counts().reset_index()
label_dist.columns = ["label", "jumlah"]
print("\n📌 Distribusi Label:")
display(label_dist)

plt.figure(figsize=(6,4))
sns.barplot(x="label", y="jumlah", data=label_dist, palette="Set2")
plt.title("Distribusi Pesan SMS (Ham vs Spam)")
plt.ylabel("Jumlah Pesan")
plt.xlabel("Label")
plt.show()

# --- 4. Statistik panjang pesan ---
df["text_length"] = df["text"].apply(len)
stats = df.groupby("label")["text_length"].describe().round(2)
print("\n📌 Statistik Panjang Pesan per Label:")
display(stats)

# --- 5. Histogram panjang pesan ---
plt.figure(figsize=(8,5))
sns.histplot(data=df, x="text_length", hue="label", bins=50, element="step", stat="density", common_norm=False)
plt.title("Distribusi Panjang Pesan (Ham vs Spam)")
plt.xlabel("Panjang SMS (jumlah karakter)")
plt.ylabel("Density")
plt.show()

# --- 6. WordCloud untuk spam & ham ---
spam_text = " ".join(df[df["label"]=="spam"]["text"])
ham_text  = " ".join(df[df["label"]=="ham"]["text"])

wc_spam = WordCloud(width=600, height=400, background_color="white", colormap="Reds").generate(spam_text)
wc_ham  = WordCloud(width=600, height=400, background_color="white", colormap="Blues").generate(ham_text)

fig, axes = plt.subplots(1,2, figsize=(14,6))
axes[0].imshow(wc_spam, interpolation="bilinear")
axes[0].set_title("WordCloud - Spam")
axes[0].axis("off")

axes[1].imshow(wc_ham, interpolation="bilinear")
axes[1].set_title("WordCloud - Ham")
axes[1].axis("off")

plt.show()

# @title label

from matplotlib import pyplot as plt
import seaborn as sns
label_dist.groupby('label').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

# @title mean

from matplotlib import pyplot as plt
stats['mean'].plot(kind='hist', bins=20, title='mean')
plt.gca().spines[['top', 'right',]].set_visible(False)

